version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    env_file: ../.env
    volumes:
      - ../db/conf:/etc/mysql/conf.d
      - ../db/dump:/docker-entrypoint-initdb.d
      # Decomment to save data in a docker volume
      # - fake-data-v1:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8000:80'
    env_file: ../.env

# volumes:
#   fake-data-v1: